# Server settings (ServerProperties)
server:
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /


spring:

  datasource:
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy

  redis:
    port: 6379
    host: localhost


---
server:
  port: 8080

spring:
  profiles: dev
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot
    username: root
    password: root

---
server:
  port: 8080

spring:
  profiles: pro
  thymeleaf:
    cache: true
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot
    username: root
    password: 123456